version: '2'
services:
  app:
    container_name: short_url_link_expander
    image: short_url_link_expander_image
    build: .
    networks:
      - main_network
    volumes:
      - ./src:/app/src
    ports:
      - 5000:5000
networks:
  main_network:
    driver: bridge